#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
#bspc rule -a mplayer2 staste=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#
# Auto Start applications


#polybar &
#nitrogen --set-scaled $HOME/Pictures/fondo.jpg
#vmware-user &
#sxhkd &
#picom --config $HOME/.config/picom/picom.conf
#nitrogen --restore &
#dunst &
#polybar &
#

sxhkd &
polybar &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
vmware-user &
wmname LG3D
nitrogen --force-setter=xwindows --set-color=#204040 --set-tiled $HOME/Pictures/Aesthetic-Wallpaper-Anime-Wallpaper-City-Night.jpg &>/dev/null
dunst &

